import Head from "next/head";
import Selectable from "../components/Selectable";
import useContextMenu from "../hooks/useContextMenu";
import Table from "../components/Table";
import QuoteBlock from "../components/QuoteBlock";
import Callout from "../components/Callout";
import List from "../components/List";
import Kanban from "../components/Kanban";
import ContextMenu from "../components/ContextMenu";
import CodeHighlight from "../components/CodeHighlight";
import CalendarView from "../components/Calendar";

export default function Home() {
  const { anchorPoint, show } = useContextMenu();

  return (
    <>
      <Head>
        <title>Untitled</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {show ? <ContextMenu anchorPoint={anchorPoint} /> : <> </>}
      <Selectable>
        <Kanban />
      </Selectable>
      <Selectable>
        <Table />
      </Selectable>
      <Selectable>
        <QuoteBlock />
      </Selectable>
      <Selectable>
        <CodeHighlight language="javascript">
        </CodeHighlight>
      </Selectable>
      <Selectable>
        <CalendarView/>
      </Selectable>
    </>
  );
}
