import Head from "next/head";
import Selectable from "../components/Selectable";
import useContextMenu from "../hooks/useContextMenu";
import Table from "../components/Table";
import QuoteBlock from "../components/QuoteBlock";

export default function Home() {
  const { anchorPoint, show } = useContextMenu();

  return (
    <>
      <Head>
        <title>Untitled</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* {show ? (
        <ContextMenu anchorPoint={anchorPoint} />
      ) : (
        <> </>
      )} */}
      <Selectable>
        <Table />
      </Selectable>
      <Selectable>
        <QuoteBlock />
      </Selectable>
    </>
  );
}
